build:
	sh echo_path.sh
	gcc myshell.c -o ../bin/myshell
	gcc dir.c -o ../bin/dir
	gcc clr.c -o ../bin/clr
	gcc environ.c -o ../bin/environ
	gcc echo.c -o ../bin/echo
	gcc cat.c -o ../bin/cat
	gcc rm.c -o ../bin/rm