#/*
# * /I/We declare  that  this  material,  which  I/We now  submit for  assessment, is  entirely  my/our own work and has not been
# * taken from the work of others, save and to the extent that such work  has  been  cited  and  acknowledged  within  the  text
# * of my/our work.  I/We understand that  plagiarism,  collusion,  and  copying  are  grave  and  serious  offences  in the
# * university  and accept  the  penalties  that  would  be  imposed  should  I  engage  in  plagiarism,  collusion  or copying.
# * I/We have read and understood the Assignment Regulations. I/We have identified and  included  the  source  of  all  facts,
# * ideas,  opinions,  and  viewpoints  of  others  in  the assignment  references.  Direct  quotations  from  books,  journal
# * articles,  internet  sources, module  text,  or  any  other  source  whatsoever  are  acknowledged  and  the  source  cited
# * are identified  in  the  assignment  references.  This  assignment,  or  any  part  of  it,  has  not  been previously
# * submitted  by  me/us or  any  other  person  for  assessment  on  this  or  any  other course of study.
# *
# * I/We have read and understood the referencing guidelines found at http://www.dcu.ie/info/regulations/plagiarism.shtml,
# * https://www4.dcu.ie/students/az/plagiarismand/or recommended in the assignment guidelines.
# *
# * Name: Malachy Byrne
# * Student Number: 19463716
#*/

build:
	sh echo_path.sh
	gcc myshell.c -o ../bin/myshell
	gcc dir.c -o ../bin/dir
	gcc clr.c -o ../bin/clr
	gcc environ.c -o ../bin/environ
	gcc echo.c -o ../bin/echo
	gcc cat.c -o ../bin/cat
	gcc rm.c -o ../bin/rm
	gcc mv.c -o ../bin/mv
	gcc help.c -o ../bin/help